version: S

task: 'test'  # train, val, test, speed or study

# weights
weights: 'runs/train/VOC/weights/best.pt'  # model path or triton URL
data: 'data/VOC.yaml'  # dataset.yaml path

# hyp
hyp: 'runs/train/VOC/hyp.yaml'

# Calibration
num_bins: 50

# Detect
batch_size: 32  # batch size
imgsz: 640  # inference size (height, width)
conf_thres_nms: 0.25  # confidence threshold
iou_thres_nms: 0.45  # NMS IOU threshold
max_det_nms: 1000  # maximum detections per image

# Output
save_txt: False  # save results to *.txt
save_hybrid: False  # save label+prediction hybrid results to *.txt
save_conf: False  # save confidences in --save-txt labels
save_json: False  # save a COCO-JSON results file
project: '../RESULTS'  # save to project/name
name: 'VOC'  # save to project/name
exist_ok: False  # existing project/name ok, do not increment

# Other
device: ''  # cuda device, i.e. 0 or 0,1,2,3 or cpu
workers: 8  # max dataloader workers (per RANK in DDP mode)
single_cls: False  # treat as single-class dataset
augment: False  # augmented inference
verbose: False  # verbose output
half: False  # use FP16 half-precision inference
dnn: False  # use OpenCV DNN for ONNX inference
model: None
dataloader: None
save_dir: Path('')
plots: True
callbacks: Callbacks()
compute_loss: None

# Added
agnostic_nms: True  # class-agnostic NMS
multi_label_nms: False